import { expect, test } from "@playwright/test";

test("legacy clothing and new props share one category, editor and search", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/e2e/fixtures/material-library.html?materialKind=clothing");
  await page.getByRole("button", { name: "素材库", exact: true }).click();
  const library = page.getByRole("dialog", { name: "素材库", exact: true });
  const category = library.getByRole("button", { name: "道具与服装", exact: true });
  await category.click();
  await expect(library.getByRole("button", { name: "道具", exact: true })).toHaveCount(0);
  await expect(library.getByRole("button", { name: "服装", exact: true })).toHaveCount(0);
  await expect(library.getByRole("button", { name: "选择素材：米色外套" })).toBeVisible();
  await library.getByRole("button", { name: "创建素材", exact: true }).click();
  const chooser = page.getByRole("dialog", { name: "创建素材", exact: true });
  await expect(chooser.getByRole("button", { name: "道具", exact: true })).toHaveCount(0);
  await expect(chooser.getByRole("button", { name: "服装", exact: true })).toHaveCount(0);
  await chooser.getByRole("button", { name: "道具与服装", exact: true }).click();
  const editor = page.locator(".ml-content-editor-dialog");
  await editor.getByRole("textbox", { name: "素材名称", exact: true }).fill("拍摄用玻璃杯");
  await editor.getByRole("textbox", { name: "道具与服装名称", exact: true }).fill("透明杯子");
  await editor.getByRole("textbox", { name: "道具与服装信息", exact: true }).fill("道具和服装共用的说明字段");
  await editor.getByRole("button", { name: "保存素材", exact: true }).click();
  await expect(editor).toBeHidden();
  await expect(library.getByRole("button", { name: "选择素材：拍摄用玻璃杯" })).toBeVisible();
  await category.click();
  await expect(library.getByRole("button", { name: /^选择素材：/ })).toHaveCount(2);
  await expect(category).toHaveAttribute("aria-pressed", "true");
  await library.getByRole("searchbox").fill("外套");
  await expect(library.getByRole("button", { name: /^选择素材：/ })).toHaveCount(1);
  await library.getByRole("searchbox").fill("");
  await expect(library.getByRole("button", { name: /^选择素材：/ })).toHaveCount(2);
  await library.getByRole("button", { name: "选择素材：米色外套" }).click();
  await library.getByRole("button", { name: "编辑素材", exact: true }).click();
  await expect(editor.getByRole("textbox", { name: "道具与服装名称", exact: true })).toHaveValue("米色外套");
  await editor.getByRole("textbox", { name: "道具与服装信息", exact: true }).fill("保留旧服装的完整内容");
  await editor.getByRole("button", { name: "保存素材", exact: true }).click();
  await expect(editor.getByText("素材已保存，可继续编辑；关闭后更新预览。")).toBeVisible();
  await editor.getByRole("button", { name: "关闭", exact: true }).click();
  await library.getByRole("button", { name: "预览", exact: true }).click();
  const preview = page.getByRole("dialog", { name: "完整组件预览", exact: true });
  await expect(preview.getByText("保留旧服装的完整内容", { exact: true })).toBeVisible();
  await preview.getByRole("button", { name: "关闭完整组件预览" }).click();
  await page.screenshot({ path: test.info().outputPath("merged-category.png"), animations: "disabled" });
  await library.getByRole("button", { name: "插入到当前文档", exact: true }).click();
  await expect(library).toBeHidden();
  await expect(page.getByRole("textbox", { name: "服装名称", exact: true })).toHaveValue("米色外套");
  await expect(page.getByRole("textbox", { name: "服装信息", exact: true })).toHaveValue("保留旧服装的完整内容");
  expect(errors).toEqual([]);
});
